name: Update china-domain-list

on:
  schedule:
    - cron: '30 15 * * *' # 中国时间+8
  workflow_dispatch:

jobs:
  update-blacklist:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Pull latest changes
      run: git pull origin main --rebase

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install requests

    - name: Run the script
      run: python update.py

    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
        git add .
        git commit -m 'ci: 👷 Update china-domain-list'
        git push
